import { db, pool } from "@workspace/db";
import { resourcesTable } from "@workspace/db";
import { sql } from "drizzle-orm";

const SEED_RESOURCES = [
  // ===== Ігри =====
  { title: "Комп'ютерна наука ігри", url: "https://itnauka.org/#games", category: "Ігри", type: "tool", difficulty: "beginner", tags: ["ігри","інформатика","інтерактивність"], description: "Колекція ігор з комп'ютерної науки на платформі itnauka.org — вчимося граючи.", language: "uk", featured: false },
  { title: "Космічна подорож", url: "https://info.ort.education/mouse/spaceadv/uk/", category: "Ігри", type: "tool", difficulty: "beginner", tags: ["ігри","алгоритми","учні"], description: "Інтерактивна гра про космічну подорож — знайомство з основами програмування для молодших школярів.", language: "uk", featured: false },
  { title: "НотаЄнота антифейкова гра", url: "https://notaenota.com/#games-block", category: "Ігри", type: "tool", difficulty: "beginner", tags: ["медіаграмотність","ігри","критичне мислення"], description: "Антифейкова гра НотаЄнота — розвиваємо медіаграмотність та критичне мислення в ігровій формі.", language: "uk", featured: false },
  { title: "Онлайн-ігри з медіаграмотності Фільтр", url: "https://filter.mcsc.gov.ua/selection/ihry-z-mediahramotnosti/", category: "Ігри", type: "tool", difficulty: "beginner", tags: ["медіаграмотність","ігри","онлайн"], description: "Підбірка онлайн-ігор з медіаграмотності від проєкту Фільтр.", language: "uk", featured: false },
  { title: "Пригоди тріски", url: "https://pragmatice.net/pragmaprodu/lecodageenchante/app/codaventure.html", category: "Ігри", type: "tool", difficulty: "beginner", tags: ["ігри","програмування","початківці"], description: "Ігровий тренажер для знайомства з основами програмування через пригодницьку гру.", language: "uk", featured: false },
  { title: "Спільнота на Wordwall — інформатика 2 клас", url: "https://wordwall.net/uk-ua/community/2-%D0%BA%D0%BB/%D1%96%D0%BD%D1%84%D0%BE%D1%80%D0%BC%D0%B0%D1%82%D0%B8%D0%BA%D0%B0", category: "Ігри", type: "platform", difficulty: "beginner", tags: ["Wordwall","ігри","2 клас","інформатика"], description: "Спільнота Wordwall з інтерактивними іграми та вправами для 2 класу з інформатики.", language: "uk", featured: false },

  // ===== Навчальні матеріали з інформатики =====
  { title: "Helpinformatik 2-11 клас", url: "https://helpinformatik.com/", category: "Навчальні матеріали з інформатики", type: "platform", difficulty: "beginner", tags: ["інформатика","уроки","2-11 клас"], description: "Сайт helpinformatik.com — навчальні матеріали з інформатики для учнів 2–11 класів.", language: "uk", featured: false },
  { title: "Informatics 5-11 клас", url: "https://sites.google.com/view/inf10/6-klas/materiali-do-urokiv?authuser=0", category: "Навчальні матеріали з інформатики", type: "platform", difficulty: "intermediate", tags: ["інформатика","5-11 клас","матеріали"], description: "Google-сайт із матеріалами до уроків інформатики для 5–11 класів.", language: "uk", featured: false },
  { title: "Інформатика 10 клас стара програма", url: "https://sites.google.com/marschool64.net/inf-10/a", category: "Навчальні матеріали з інформатики", type: "platform", difficulty: "intermediate", tags: ["інформатика","10 клас","стара програма"], description: "Матеріали з інформатики для 10 класу за старою програмою (школа 64).", language: "uk", featured: false },
  { title: "Інформатика 10 клас", url: "https://sites.google.com/marschool64.net/inf-10/", category: "Навчальні матеріали з інформатики", type: "platform", difficulty: "intermediate", tags: ["інформатика","10 клас"], description: "Навчальний сайт з інформатики для 10 класу школи 64.", language: "uk", featured: false },
  { title: "Інформатика 3-4 клас", url: "https://sofiiainf.blogspot.com/p/4.html", category: "Навчальні матеріали з інформатики", type: "article", difficulty: "beginner", tags: ["інформатика","3-4 клас","НУШ"], description: "Блог учителя з матеріалами та завданнями з інформатики для 3–4 класів.", language: "uk", featured: false },
  { title: "Інформатика 5-11 клас Семчак", url: "https://sites.google.com/view/semchak/", category: "Навчальні матеріали з інформатики", type: "platform", difficulty: "intermediate", tags: ["інформатика","5-11 клас","Семчак"], description: "Персональний навчальний сайт Семчак — матеріали з інформатики для 5–11 класів.", language: "uk", featured: false },
  { title: "Інформатика 8 клас стара програма", url: "https://sites.google.com/marschool64.net/informatika-8/", category: "Навчальні матеріали з інформатики", type: "platform", difficulty: "intermediate", tags: ["інформатика","8 клас","стара програма"], description: "Матеріали з інформатики для 8 класу за старою програмою.", language: "uk", featured: false },
  { title: "Інформатікс сайт Олійник Світлани 5-9 клас", url: "https://inform54.wordpress.com/", category: "Навчальні матеріали з інформатики", type: "article", difficulty: "intermediate", tags: ["інформатика","5-9 клас","блог вчителя"], description: "WordPress-блог Олійник Світлани з матеріалами до уроків інформатики для 5–9 класів.", language: "uk", featured: false },
  { title: "Блог Кристапчук Оксани", url: "https://kristapchukoksana.blogspot.com/", category: "Навчальні матеріали з інформатики", type: "article", difficulty: "beginner", tags: ["блог вчителя","інформатика","уроки"], description: "Блог вчителя інформатики Кристапчук Оксани з матеріалами та ідеями для уроків.", language: "uk", featured: false },
  { title: "Блог Терлецької Інни 5-11 клас", url: "https://innaterletska.blogspot.com/p/8.html", category: "Навчальні матеріали з інформатики", type: "article", difficulty: "intermediate", tags: ["блог вчителя","інформатика","5-11 клас"], description: "Блог Терлецької Інни — великий архів корисних матеріалів з інформатики для 5–11 класів.", language: "uk", featured: false },
  { title: "Блог вчителя інформатики Прядуна 2-9 класи", url: "https://teach.in.ua/3-4/4", category: "Навчальні матеріали з інформатики", type: "article", difficulty: "beginner", tags: ["блог вчителя","інформатика","2-9 клас"], description: "Сайт Прядуна — матеріали, розробки уроків та тести з інформатики для 2–9 класів.", language: "uk", featured: false },
  { title: "Блог вчителів інформатики 5-11 клас", url: "https://informatikpereginska.blogspot.com/p/9_7.html", category: "Навчальні матеріали з інформатики", type: "article", difficulty: "intermediate", tags: ["блог вчителя","інформатика","5-11 клас"], description: "Колективний блог вчителів інформатики з розробками уроків для 5–11 класів.", language: "uk", featured: false },
  { title: "Вивчаємо Python", url: "https://pishachok.blogspot.com/p/blog-page_37.html", category: "Навчальні матеріали з інформатики", type: "article", difficulty: "beginner", tags: ["Python","програмування","навчання"], description: "Покрокові матеріали для вивчення Python — від основ до практичних завдань.", language: "uk", featured: false },
  { title: "Всеосвіта", url: "https://vseosvita.ua/test", category: "Навчальні матеріали з інформатики", type: "platform", difficulty: "beginner", tags: ["тести","всеосвіта","онлайн-навчання"], description: "Освітня платформа Всеосвіта — тести, розробки уроків і навчальні матеріали.", language: "uk", featured: false },
  { title: "Віртуальний кабінет інформатики 5-11 класи", url: "https://sites.google.com/view/teacherschool5/", category: "Навчальні матеріали з інформатики", type: "platform", difficulty: "intermediate", tags: ["інформатика","5-11 клас","матеріали"], description: "Віртуальний кабінет інформатики — навчальні матеріали та ресурси для уроків 5–11 класів.", language: "uk", featured: false },
  { title: "ДистОсвіта", url: "https://dystosvita.org.ua/", category: "Навчальні матеріали з інформатики", type: "platform", difficulty: "beginner", tags: ["дистанційна освіта","платформа","вчителям"], description: "Платформа ДистОсвіта — ресурси та підтримка для дистанційного навчання.", language: "uk", featured: false },
  { title: "Електронний документообіг 10 клас", url: "https://docs.google.com/spreadsheets/d/e/2PACX-1vQxAj8VC8BXUIo7ru7q9wBsvpfZwxi_1pddcM3AKw5uj8JlwTxz466qbmy7SNFv2NbWqoV21b6J0f2E/pubhtml", category: "Навчальні матеріали з інформатики", type: "article", difficulty: "intermediate", tags: ["документообіг","10 клас","Google Таблиці"], description: "Таблиця Google з матеріалами до теми Електронний документообіг для 10 класу.", language: "uk", featured: false },
  { title: "ЗОШ 19 — корисне для уроків", url: "https://sites.google.com/site/informatikackua19/", category: "Навчальні матеріали з інформатики", type: "platform", difficulty: "beginner", tags: ["інформатика","6 клас","НУШ"], description: "Сайт інформатики ЗОШ 19 — матеріали, посилання та корисне для уроків і не тільки.", language: "uk", featured: false },
  { title: "Комп'ютерна наука з паном Артемом 3-7 клас", url: "https://itnauka.org/#digital-tools", category: "Навчальні матеріали з інформатики", type: "platform", difficulty: "beginner", tags: ["комп'ютерна наука","3-7 клас","цифрові інструменти"], description: "Платформа пана Артема — уроки з комп'ютерної науки для учнів 3–7 класів.", language: "uk", featured: false },
  { title: "Корисні посилання для учнів (Prometheus)", url: "https://apps.prometheus.org.ua/learner-dashboard/", category: "Навчальні матеріали з інформатики", type: "platform", difficulty: "beginner", tags: ["Prometheus","онлайн-курси","учні"], description: "Особистий кабінет учня на Prometheus — доступ до курсів та навчальних матеріалів.", language: "uk", featured: false },
  { title: "МійКлас 2-4 клас", url: "https://www.miyklas.com.ua/p/informatika-nush", category: "Навчальні матеріали з інформатики", type: "platform", difficulty: "beginner", tags: ["НУШ","2-4 клас","інформатика","МійКлас"], description: "Навчальна платформа МійКлас — матеріали з інформатики НУШ для 2–4 класів.", language: "uk", featured: false },
  { title: "На урок", url: "https://naurok.com.ua/test/homework/list", category: "Навчальні матеріали з інформатики", type: "platform", difficulty: "beginner", tags: ["тести","На урок","домашні завдання"], description: "Платформа На урок — тести, домашні завдання та навчальні матеріали для вчителів.", language: "uk", featured: false },
  { title: "Онлайн-конспекти з інформатики 5-10 класи", url: "https://sites.google.com/view/onlayn-konspekt-z-informatiku/", category: "Навчальні матеріали з інформатики", type: "platform", difficulty: "intermediate", tags: ["конспекти","5-10 клас","інформатика"], description: "Google-сайт з онлайн-конспектами уроків інформатики для 5–10 класів.", language: "uk", featured: false },
  { title: "Освітня платформа ВЧИМО", url: "https://vchymo.com/app/application", category: "Навчальні матеріали з інформатики", type: "platform", difficulty: "beginner", tags: ["ВЧИМО","онлайн-навчання","платформа"], description: "Освітня платформа ВЧИМО — інтерактивні завдання та матеріали для учнів та вчителів.", language: "uk", featured: false },
  { title: "Персональний сайт Чашука Олександра", url: "http://chashuk.edukit.volyn.ua/", category: "Навчальні матеріали з інформатики", type: "article", difficulty: "intermediate", tags: ["інформатика","5-11 клас","блог вчителя"], description: "Персональний сайт вчителя інформатики Чашука Олександра з матеріалами для 5–11 класів.", language: "uk", featured: false },
  { title: "Презентації до уроків — блог Оніцук Ганни", url: "https://onishchukanna.blogspot.com/", category: "Навчальні матеріали з інформатики", type: "article", difficulty: "intermediate", tags: ["презентації","5-11 клас","блог вчителя"], description: "Блог Оніцук Ганни — архів презентацій до уроків інформатики для 5–11 класів.", language: "uk", featured: false },
  { title: "Сайт інформатики Ніколаєнко", url: "https://sites.google.com/view/nikolaenko-informat/", category: "Навчальні матеріали з інформатики", type: "platform", difficulty: "intermediate", tags: ["інформатика","сайт вчителя","матеріали"], description: "Сайт вчителя інформатики Ніколаєнко — навчальні матеріали та ресурси до уроків.", language: "uk", featured: false },
  { title: "Учительський сайт Бойка 5-11 клас", url: "https://informatboyk.blogspot.com/", category: "Навчальні матеріали з інформатики", type: "article", difficulty: "intermediate", tags: ["блог вчителя","5-11 клас","інформатика"], description: "Блог вчителя інформатики Бойка — матеріали, завдання та ресурси для 5–11 класів.", language: "uk", featured: false },
  { title: "Цифрова школа — Ed-Era курси", url: "https://www.ed-era.com/courses", category: "Навчальні матеріали з інформатики", type: "platform", difficulty: "intermediate", tags: ["Ed-Era","онлайн-курси","цифрова освіта"], description: "Платформа Ed-Era — онлайн-курси та матеріали з різних предметів для середньої і старшої школи.", language: "uk", featured: false },
  { title: "Шкільний сайт Онопрієнко 5-9 клас", url: "https://onopriyenkoinf.blogspot.com/", category: "Навчальні матеріали з інформатики", type: "article", difficulty: "intermediate", tags: ["блог вчителя","5-9 клас","інформатика"], description: "Блог вчителя інформатики Онопрієнко — уроки та матеріали для 5–9 класів.", language: "uk", featured: false },

  // ===== Робота з ШІ =====
  { title: "Adobe Firefly — генерація зображень", url: "https://firefly.adobe.com/", category: "Робота з ШІ", type: "tool", difficulty: "beginner", tags: ["Adobe","генерація зображень","ШІ"], description: "Adobe Firefly — ШІ-інструмент від Adobe для генерації та редагування зображень.", language: "uk", featured: false },
  { title: "ChatGPT", url: "https://chatgpt.com/", category: "Робота з ШІ", type: "tool", difficulty: "beginner", tags: ["ChatGPT","ШІ","чат-бот"], description: "ChatGPT від OpenAI — потужний ШІ-помічник для текстових завдань, навчання та творчості.", language: "uk", featured: true },
  { title: "Copilot Microsoft", url: "https://copilot.microsoft.com/", category: "Робота з ШІ", type: "tool", difficulty: "beginner", tags: ["Microsoft","Copilot","ШІ"], description: "Microsoft Copilot — ШІ-асистент, інтегрований у продукти Microsoft 365.", language: "uk", featured: false },
  { title: "Gemini Google", url: "https://gemini.google.com/", category: "Робота з ШІ", type: "tool", difficulty: "beginner", tags: ["Google","Gemini","ШІ"], description: "Google Gemini — мультимодальна ШІ-модель для роботи з текстом, зображеннями та кодом.", language: "uk", featured: false },
  { title: "Ideogram — генерація зображень", url: "https://ideogram.ai/", category: "Робота з ШІ", type: "tool", difficulty: "beginner", tags: ["генерація зображень","ШІ","Ideogram"], description: "Ideogram AI — безкоштовний інструмент для генерації зображень за текстовим описом.", language: "uk", featured: false },
  { title: "Leonardo AI — генерація зображень", url: "https://app.leonardo.ai/", category: "Робота з ШІ", type: "tool", difficulty: "intermediate", tags: ["Leonardo AI","генерація зображень","ШІ"], description: "Leonardo AI — платформа для генерації якісних зображень та арту за допомогою ШІ.", language: "uk", featured: false },
  { title: "Mistral AI", url: "https://mistral.ai/", category: "Робота з ШІ", type: "tool", difficulty: "intermediate", tags: ["Mistral","ШІ","LLM"], description: "Mistral AI — відкрита мовна модель для чату, написання коду та аналізу тексту.", language: "uk", featured: false },
  { title: "NotebookLM Google", url: "https://notebooklm.google.com/", category: "Робота з ШІ", type: "tool", difficulty: "beginner", tags: ["Google","NotebookLM","дослідження"], description: "Google NotebookLM — ШІ-помічник для роботи з документами, нотатками та дослідженнями.", language: "uk", featured: false },
  { title: "Perplexity", url: "https://www.perplexity.ai/", category: "Робота з ШІ", type: "tool", difficulty: "beginner", tags: ["Perplexity","пошук","ШІ"], description: "Perplexity AI — інтелектуальна пошукова система з відповідями від ШІ та посиланнями на джерела.", language: "uk", featured: false },
  { title: "Pixso — створення дизайнів", url: "https://pixso.net/", category: "Робота з ШІ", type: "tool", difficulty: "intermediate", tags: ["дизайн","Pixso","прототипування"], description: "Pixso — онлайн-інструмент для UI/UX-дизайну та прототипування з підтримкою ШІ.", language: "uk", featured: false },
  { title: "Poe ШІ", url: "https://poe.com/", category: "Робота з ШІ", type: "tool", difficulty: "beginner", tags: ["Poe","ШІ","чат-боти"], description: "Poe від Quora — платформа з доступом до різних ШІ-моделей в одному місці.", language: "uk", featured: false },
  { title: "Replit Agent", url: "https://replit.com/products/agent", category: "Робота з ШІ", type: "tool", difficulty: "intermediate", tags: ["Replit","програмування","ШІ-агент"], description: "Replit Agent — ШІ-асистент для програмування, що допомагає будувати застосунки з нуля.", language: "uk", featured: false },
  { title: "Sider", url: "https://sider.ai/", category: "Робота з ШІ", type: "tool", difficulty: "beginner", tags: ["Sider","ШІ","браузерний помічник"], description: "Sider — ШІ-помічник у браузері для роботи з текстом, перекладу та навчання.", language: "uk", featured: false },
  { title: "Slidesgo", url: "https://slidesgo.com/", category: "Робота з ШІ", type: "tool", difficulty: "beginner", tags: ["презентації","Slidesgo","шаблони"], description: "Slidesgo — безкоштовні шаблони презентацій з підтримкою ШІ для вчителів та учнів.", language: "uk", featured: false },
  { title: "Solo — створення вебсайту", url: "https://soloist.ai/", category: "Робота з ШІ", type: "tool", difficulty: "beginner", tags: ["вебсайт","ШІ","конструктор"], description: "Solo — ШІ-конструктор вебсайтів без коду: опишіть ідею і отримайте готовий сайт.", language: "uk", featured: false },
  { title: "Vidu — створення відео", url: "https://www.vidu.com/", category: "Робота з ШІ", type: "tool", difficulty: "beginner", tags: ["відео","ШІ","генерація"], description: "Vidu — ШІ-інструмент для генерації відеоконтенту за текстовим описом.", language: "uk", featured: false },
  { title: "Обмін обличчями — AI Face Swap", url: "https://aifaceswap.io/", category: "Робота з ШІ", type: "tool", difficulty: "beginner", tags: ["face swap","ШІ","зображення"], description: "AI Face Swap — онлайн-інструмент для заміни облич на фото за допомогою ШІ.", language: "uk", featured: false },
  { title: "Персональні асистенти — підбірка", url: "https://crenius.notion.site/6-03-02-25-161188568e9f8081b40cc39badf04fc5", category: "Робота з ШІ", type: "article", difficulty: "beginner", tags: ["ШІ-асистенти","Notion","підбірка"], description: "Підбірка персональних ШІ-асистентів із Notion-сторінки — корисний огляд інструментів.", language: "uk", featured: false },
  { title: "Як правильно створювати запити для ШІ", url: "https://www.youtube.com/live/oxSR5yuos-M", category: "Робота з ШІ", type: "video", difficulty: "beginner", tags: ["промпти","ШІ","YouTube","навчання"], description: "Відео-урок про мистецтво написання ефективних промптів для роботи зі штучним інтелектом.", language: "uk", featured: false },

  // ===== Різне =====
  { title: "EPAM програми навчання", url: "https://campus.epam.ua/ua/training", category: "Різне", type: "course", difficulty: "advanced", tags: ["EPAM","навчання","IT"], description: "EPAM Campus — безкоштовні навчальні програми та курси для майбутніх IT-спеціалістів.", language: "uk", featured: false },
  { title: "Excel з нуля за 1,5 години", url: "https://www.youtube.com/live/uRARDyN7pvk", category: "Різне", type: "video", difficulty: "beginner", tags: ["Excel","YouTube","таблиці"], description: "Відео-урок: освоїти Excel з абсолютного нуля за 1,5 години — практичний інтенсив.", language: "uk", featured: false },
  { title: "MagicSchool курси для вчителів", url: "https://www.magicschool.ai/certification-courses", category: "Різне", type: "course", difficulty: "beginner", tags: ["MagicSchool","ШІ","вчителям"], description: "MagicSchool — сертифікаційні курси для вчителів щодо використання ШІ в освіті.", language: "uk", featured: false },
  { title: "Prometheus — онлайн-курси", url: "https://apps.prometheus.org.ua/learner-dashboard/", category: "Різне", type: "platform", difficulty: "beginner", tags: ["Prometheus","онлайн-курси","безкоштовно"], description: "Prometheus — провідна українська платформа безкоштовних онлайн-курсів з різних дисциплін.", language: "uk", featured: true },
  { title: "Teachers winter 2025 — підбірка ресурсів", url: "https://crenius.notion.site/Teachers-winter-2025-161188568e9f80909021e0c25c4336c2", category: "Різне", type: "article", difficulty: "beginner", tags: ["вчителям","Notion","підбірка 2025"], description: "Notion-сторінка з підбіркою ресурсів і матеріалів для вчителів — зимовий випуск 2025.", language: "uk", featured: false },
  { title: "Інтерактивна інформатика", url: "https://interact-lessons.com/", category: "Різне", type: "platform", difficulty: "beginner", tags: ["інтерактивні уроки","інформатика","навчання"], description: "Платформа Інтерактивна інформатика — готові інтерактивні уроки та матеріали для вчителів.", language: "uk", featured: false },
  { title: "Вікторина Хто краще — 8 клас", url: "https://wordwall.net/uk/resource/57013830/", category: "Різне", type: "tool", difficulty: "intermediate", tags: ["вікторина","8 клас","Wordwall","інформатика"], description: "Вікторина з інформатики для 8 класу на Wordwall — Хто краще знає матеріал?", language: "uk", featured: false },
  { title: "Дія Освіта", url: "https://osvita.diia.gov.ua/about", category: "Різне", type: "platform", difficulty: "beginner", tags: ["Дія","освіта","держпослуги"], description: "Дія.Освіта — державна платформа для безперервного навчання та розвитку цифрових навичок.", language: "uk", featured: false },
  { title: "Знайшов — освітні новини", url: "https://znayshov.com/news", category: "Різне", type: "platform", difficulty: "beginner", tags: ["новини","освіта","Україна"], description: "Знайшов.com — агрегатор освітніх новин та корисного контенту для педагогів.", language: "uk", featured: false },
  { title: "Календар для вчителя", url: "https://alexmyz.github.io/calendar-plan/", category: "Різне", type: "tool", difficulty: "beginner", tags: ["календар","планування","вчителям"], description: "Онлайн-календар для вчителя — зручне планування навчального розкладу та подій.", language: "uk", featured: false },
  { title: "Осьо — каталог українських діджитал-продуктів", url: "https://osyo.app/", category: "Різне", type: "platform", difficulty: "beginner", tags: ["каталог","українські продукти","діджитал"], description: "Osyo — каталог українських цифрових продуктів і сервісів, корисних для роботи та навчання.", language: "uk", featured: false },
  { title: "Платформа Вектор", url: "https://vector.uied.gov.ua/", category: "Різне", type: "platform", difficulty: "beginner", tags: ["Вектор","підвищення кваліфікації","педагоги"], description: "Вектор — платформа для підвищення кваліфікації педагогів від МОН України.", language: "uk", featured: false },
  { title: "Платформа для педагогів Уміти", url: "https://umity.in.ua/", category: "Різне", type: "platform", difficulty: "beginner", tags: ["Уміти","педагоги","навчання"], description: "Уміти — освітня платформа для розвитку педагогічних компетентностей вчителів.", language: "uk", featured: false },
  { title: "Проактивний педагог — ШІ в освіті", url: "https://educationpakhomova.blogspot.com/p/artificial-intelligence-in-education_26.html", category: "Різне", type: "article", difficulty: "beginner", tags: ["ШІ в освіті","блог","педагог"], description: "Блог Іринт Пахомової — стаття про штучний інтелект в освіті для проактивних педагогів.", language: "uk", featured: false },
  { title: "Стаття про безкоштовний ChatGPT", url: "https://theinweb.media/yak-bezkoshtovno-vikoristovuvati-chatgpt-4/", category: "Різне", type: "article", difficulty: "beginner", tags: ["ChatGPT","безкоштовно","ШІ"], description: "Стаття: як безкоштовно використовувати ChatGPT-4 — практичні поради для вчителів та учнів.", language: "uk", featured: false },
  { title: "Теми проєктів з інформатики", url: "https://fiz-patlay.blogspot.com/p/blog-page_19.html", category: "Різне", type: "article", difficulty: "intermediate", tags: ["проєкти","інформатика","ідеї"], description: "Підбірка тем для учнівських проєктів з інформатики — готові ідеї для дослідницької роботи.", language: "uk", featured: false },
  { title: "ШІ для педагогів", url: "https://educationpakhomova.blogspot.com/p/ai-in-education.html", category: "Різне", type: "article", difficulty: "beginner", tags: ["ШІ","педагоги","інструменти"], description: "Огляд ШІ-інструментів для педагогів — як використовувати штучний інтелект у навчанні.", language: "uk", featured: false },
  { title: "Шрифт, який не бачить ШІ", url: "https://dou.ua/forums/topic/60797/", category: "Різне", type: "article", difficulty: "intermediate", tags: ["ШІ","шрифт","DOU","цікаво"], description: "Стаття на DOU про шрифт, що обходить системи розпізнавання тексту ШІ — цікавий кейс.", language: "uk", featured: false },
  { title: "Шрифтова абетка — українська ідентичність", url: "https://abetkaua.com/", category: "Різне", type: "platform", difficulty: "beginner", tags: ["шрифти","українська мова","ідентичність"], description: "Абетка UA — каталог шрифтів з українською ідентичністю для дизайнерів та вчителів.", language: "uk", featured: false },
  { title: "Як працювати в Blender — відео", url: "https://www.youtube.com/watch?v=7TVdJCoe3lc", category: "Різне", type: "video", difficulty: "intermediate", tags: ["Blender","3D","YouTube","творчість"], description: "Відео-урок зі вступу до Blender — 3D-моделювання для початківців.", language: "uk", featured: false },
  { title: "Як працює ШІ — відео пояснення", url: "https://www.youtube.com/watch?v=sUG-L87RxZs", category: "Різне", type: "video", difficulty: "beginner", tags: ["ШІ","YouTube","пояснення"], description: "Відео-пояснення принципів роботи штучного інтелекту — доступно та зрозуміло.", language: "uk", featured: false },
  { title: "Роботи перформанс 2026", url: "https://www.youtube.com/watch?v=LPEGve_U1cY", category: "Різне", type: "video", difficulty: "beginner", tags: ["роботи","YouTube","технології"], description: "YouTube-відео: виступ роботів-перформерів 2026 року — технології майбутнього вже сьогодні.", language: "uk", featured: false },
  { title: "Rutor — відеоматеріали", url: "https://rutor.info/torrent/197715/", category: "Різне", type: "platform", difficulty: "beginner", tags: ["кіно","відео","розваги"], description: "Rutor — трекер для пошуку та завантаження відеоматеріалів та фільмів.", language: "uk", featured: false },
  { title: "Рандомне кіно — вибір фільму", url: "https://nothing-to-watch.port80.ch/", category: "Різне", type: "tool", difficulty: "beginner", tags: ["кіно","рекомендації","розваги"], description: "Сервіс для вибору випадкового фільму на вечір — якщо не знаєш, що подивитися.", language: "uk", featured: false },

  // ===== Творчість =====
  { title: "Adobe Express", url: "https://new.express.adobe.com/", category: "Творчість", type: "tool", difficulty: "beginner", tags: ["Adobe","дизайн","візуальний контент"], description: "Adobe Express — безкоштовний онлайн-редактор для створення плакатів, відео та графіки.", language: "uk", featured: false },
  { title: "Blogger", url: "https://www.blogger.com/about/", category: "Творчість", type: "tool", difficulty: "beginner", tags: ["блог","Blogger","Google","письменництво"], description: "Blogger від Google — безкоштовна платформа для створення власного блогу або сайту класу.", language: "uk", featured: false },
  { title: "Caligraphr — власний шрифт", url: "https://www.calligraphr.com/en/", category: "Творчість", type: "tool", difficulty: "intermediate", tags: ["шрифти","каліграфія","творчість"], description: "Calligraphr — сервіс для створення власного рукописного шрифту з вашого почерку.", language: "uk", featured: false },
  { title: "Canva", url: "https://www.canva.com/", category: "Творчість", type: "tool", difficulty: "beginner", tags: ["Canva","дизайн","презентації"], description: "Canva — найпопулярніший онлайн-редактор для дизайну: презентації, плакати, соцмережі.", language: "uk", featured: true },
  { title: "Flinga — спільна дошка", url: "https://flinga.fi/s/FM256VY", category: "Творчість", type: "tool", difficulty: "beginner", tags: ["Flinga","колаборація","інтерактивна дошка"], description: "Flinga — спільна інтерактивна дошка для командної роботи та мозкових штурмів на уроці.", language: "uk", featured: false },
  { title: "JSFiddle — онлайн-редактор коду", url: "https://jsfiddle.net/g7jh8mrc/", category: "Творчість", type: "tool", difficulty: "intermediate", tags: ["JavaScript","HTML","CSS","кодування"], description: "JSFiddle — онлайн-редактор HTML/CSS/JavaScript для практики веброзробки прямо в браузері.", language: "uk", featured: false },
  { title: "Mentimeter — інтерактивні опитування", url: "https://www.mentimeter.com/", category: "Творчість", type: "tool", difficulty: "beginner", tags: ["Mentimeter","опитування","інтерактивність"], description: "Mentimeter — інструмент для інтерактивних опитувань і голосувань в реальному часі на уроці.", language: "uk", featured: false },
  { title: "Scratch — програмування для дітей", url: "https://scratch.mit.edu/projects/editor/?tutorial=getStarted", category: "Творчість", type: "tool", difficulty: "beginner", tags: ["Scratch","програмування","MIT","діти"], description: "Scratch від MIT — безкоштовне середовище для вивчення програмування через візуальні блоки.", language: "uk", featured: true },
  { title: "Wakelet — колекції посилань", url: "https://wakelet.com/", category: "Творчість", type: "tool", difficulty: "beginner", tags: ["Wakelet","колекції","освіта"], description: "Wakelet — платформа для створення та ділення колекцій посилань, відео та матеріалів.", language: "uk", featured: false },
  { title: "Wayground — навчальні ігри", url: "https://wayground.com/", category: "Творчість", type: "tool", difficulty: "beginner", tags: ["вікторина","гейміфікація","навчання"], description: "Wayground — платформа для створення навчальних ігор та вікторин для учнів.", language: "uk", featured: false },
  { title: "Wordwall — конструктор вправ", url: "https://wordwall.net/uk/community", category: "Творчість", type: "tool", difficulty: "beginner", tags: ["Wordwall","ігри","інтерактивні вправи"], description: "Wordwall — конструктор інтерактивних ігор та вправ для уроків: вікторини, сортування, кросворди.", language: "uk", featured: false },
  { title: "Приклад сторінки HTML", url: "https://jsfiddle.net/eoh60t8k/", category: "Творчість", type: "tool", difficulty: "beginner", tags: ["HTML","приклад","веброзробка"], description: "Приклад простої HTML-сторінки на JSFiddle — для демонстрації основ розмітки учням.", language: "uk", featured: false },
  { title: "Створення шкали часу", url: "https://time.graphics/editor", category: "Творчість", type: "tool", difficulty: "beginner", tags: ["шкала часу","timeline","інтерактивність"], description: "Time.graphics — безкоштовний онлайн-редактор для створення інтерактивних шкал часу.", language: "uk", featured: false },
];

export async function seedIfEmpty(): Promise<void> {
  try {
    // Ensure table exists
    await pool.query(`
      CREATE TABLE IF NOT EXISTS resources (
        id SERIAL PRIMARY KEY,
        title TEXT NOT NULL,
        description TEXT NOT NULL DEFAULT '',
        url TEXT NOT NULL,
        category TEXT NOT NULL,
        tags TEXT[] NOT NULL DEFAULT '{}',
        type TEXT NOT NULL DEFAULT 'article',
        difficulty TEXT NOT NULL DEFAULT 'beginner',
        language TEXT DEFAULT 'uk',
        featured BOOLEAN NOT NULL DEFAULT false,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      )
    `);

    // Add unique constraint if missing
    await pool.query(`
      DO $$ BEGIN
        ALTER TABLE resources ADD CONSTRAINT resources_url_unique UNIQUE (url);
      EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL;
      END $$;
    `);

    // Check if already seeded
    const { rows } = await pool.query(`SELECT COUNT(*) AS cnt FROM resources`);
    const count = parseInt(rows[0].cnt, 10);

    if (count > 0) {
      return; // already has data, skip
    }

    // Insert all seed resources
    for (const r of SEED_RESOURCES) {
      await pool.query(
        `INSERT INTO resources (title, description, url, category, tags, type, difficulty, language, featured, created_at, updated_at)
         VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,NOW(),NOW())
         ON CONFLICT (url) DO NOTHING`,
        [r.title, r.description, r.url, r.category, r.tags, r.type, r.difficulty, r.language, r.featured]
      );
    }

    console.log(`[seed] Inserted ${SEED_RESOURCES.length} resources`);
  } catch (err) {
    console.error("[seed] Error during seeding:", err);
    // Don't crash the server on seed failure
  }
}
